import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/Hero";
import Footer from "@/components/Footer";
import BackToTopButton from "@/components/BackToTopButton";
import { Toaster } from "react-hot-toast";

// Load Inter from Google Fonts (for body text)
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Load CanelaTrial as a Local Font

const canelaTrial = localFont({
  src: "../public/fonts/Canela-Regular-Trial.woff2", // Path to font file
  variable: "--font-header",
  display: "swap", // Prevents layout shift
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${canelaTrial.variable} antialiased`}>
        <Toaster position="top-right" />
        <Navbar />
        <div className="mt-[100px]">
          <HeroSection />
          <div>{children}</div>
          <Footer />
          <BackToTopButton />
        </div>
      </body>
    </html>
  );
}
