import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import LayoutWrapper from "@/components/LayoutWrapper";

// Load Inter from Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Load CanelaTrial as a Local Font
const canelaTrial = localFont({
  src: "../public/fonts/Canela-Regular-Trial.woff2",
  variable: "--font-header",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${canelaTrial.variable} antialiased`}>
        <Toaster position="top-right" />
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
