import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import HeroSection from "@/components/Hero";
import Footer from "@/components/Footer";
import BackToTopButton from "@/components/BackToTopButton";

// Inter as the main font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// CanelaTrial as the header font (ensure the file exists in /public/fonts/)
// const headerFont = localFont({
//   src: "../public/fonts/CanelaTrial.woff2",
//   variable: "--font-header",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased`}>
        <Navbar />
        <div className="mt-[100px]">
          <HeroSection />
          <div>{children}</div>
          <Footer />
          <BackToTopButton />
        </div>
      </body>
    </html>
  );
}
